"""add budget_alerts table

Revision ID: b7f3a9c1d2e4
Revises: 8b3e1a7c9d42
Create Date: 2026-07-05 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f3a9c1d2e4'
down_revision = '8b3e1a7c9d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'budget_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('threshold', sa.Integer(), nullable=False),
        sa.Column('recipient', sa.String(length=32), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'week_start', 'threshold', 'recipient',
            name='uq_budget_alerts_week_threshold_recipient',
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_alerts')
    # ### end Alembic commands ###
